/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.alumnogui;

import dao.AlumnoDAOSql;
import dao.AlumnoDAOTxt;
import dao.DAO;
import dao.DAOException;
import dao.DAOFactory;
import dao.DAOFactoryException;
import enums.CrudAction;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableModel;
import persona.Alumno;
import exceptions.EstadoException;

/**
 *
 * @author g.guzman
 */
public class AlumnoGUI extends javax.swing.JFrame {

    private DAO<Alumno, Integer> dao;
    private AlumnoDAOTxt daoTXT;
    private AlumnoDAOSql daoSQL;
    private final AlumnosTableModel alumnosModel;
    private List<Alumno> alumnos;
    
    /**
     * Creates new form AlumnoGUI
     */
    public AlumnoGUI() {
        initComponents();
        setLocationRelativeTo(null);
        txtPanel.setVisible(repoComboBox.getSelectedIndex()==0);
        sqlPanel.setVisible(repoComboBox.getSelectedIndex()==1);
        
        alumnosModel = new AlumnosTableModel();
        alumnosTable.setModel(alumnosModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        alumnosTable = new javax.swing.JTable();
        crearButton = new javax.swing.JButton();
        modificarButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        consultarButton = new javax.swing.JButton();
        incluirCheckBox = new javax.swing.JCheckBox();
        txtPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fullpathTextField = new javax.swing.JTextField();
        chooserButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        repoComboBox = new javax.swing.JComboBox<>();
        sqlPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        urlTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        userTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pwdTextField = new javax.swing.JTextField();
        connSQLButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        alumnosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(alumnosTable);

        crearButton.setText("Crear");
        crearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearButtonActionPerformed(evt);
            }
        });

        modificarButton.setText("Modificar");
        modificarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Eliminar");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        consultarButton.setText("Consultar");
        consultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarButtonActionPerformed(evt);
            }
        });

        incluirCheckBox.setText("Incluir Eliminados");
        incluirCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluirCheckBoxActionPerformed(evt);
            }
        });

        txtPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Ruta archivo:");

        fullpathTextField.setEditable(false);
        fullpathTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullpathTextFieldActionPerformed(evt);
            }
        });

        chooserButton.setText("...");
        chooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout txtPanelLayout = new javax.swing.GroupLayout(txtPanel);
        txtPanel.setLayout(txtPanelLayout);
        txtPanelLayout.setHorizontalGroup(
            txtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fullpathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooserButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        txtPanelLayout.setVerticalGroup(
            txtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fullpathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooserButton))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel2.setText("Tipo de Repositorio:");

        repoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TXT", "SQL" }));
        repoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repoComboBoxActionPerformed(evt);
            }
        });

        sqlPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("URL:");

        urlTextField.setText("jdbc:mysql://localhost:3306/alumnos");
        urlTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("User:");

        userTextField.setText("caba");
        userTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Clave:");

        pwdTextField.setText("root");
        pwdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdTextFieldActionPerformed(evt);
            }
        });

        connSQLButton.setText("Conectar");
        connSQLButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connSQLButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sqlPanelLayout = new javax.swing.GroupLayout(sqlPanel);
        sqlPanel.setLayout(sqlPanelLayout);
        sqlPanelLayout.setHorizontalGroup(
            sqlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sqlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sqlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sqlPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pwdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(connSQLButton, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                    .addGroup(sqlPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(urlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sqlPanelLayout.setVerticalGroup(
            sqlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sqlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sqlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(urlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sqlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sqlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(pwdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(connSQLButton))
                    .addGroup(sqlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(incluirCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modificarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(consultarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(36, 36, 36)
                                .addComponent(repoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sqlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(repoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sqlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(incluirCheckBox)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(crearButton)
                        .addGap(18, 18, 18)
                        .addComponent(modificarButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton)
                        .addGap(18, 18, 18)
                        .addComponent(consultarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void repoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repoComboBoxActionPerformed
        /*
        txtPanel.setVisible(repoComboBox.getSelectedIndex()==0);
        sqlPanel.setVisible(repoComboBox.getSelectedIndex()==1);
        */
        if (repoComboBox.getSelectedIndex()==0) {
            if (daoTXT!=null) {
                dao = daoTXT;
            }
            txtPanel.setVisible(true);
            sqlPanel.setVisible(false);
        }
        else {
            if (daoSQL!=null) {
                dao = daoSQL;
            }
            txtPanel.setVisible(false);
            sqlPanel.setVisible(true);
        }

    }//GEN-LAST:event_repoComboBoxActionPerformed

    private void chooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooserButtonActionPerformed
          JFileChooser fileChooser = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter(null, "txt", "json");
        fileChooser.setFileFilter(filter);
        int resp = fileChooser.showOpenDialog(this);
        if (resp!=JFileChooser.APPROVE_OPTION) {
            return;
        }        
        fullpathTextField.setText(fileChooser.getSelectedFile().getAbsolutePath());
        try {
            Map<String, String> config = new HashMap<>();
            config.put(DAOFactory.TIPO_DAO, "TIPO_DAO_TXT");
            config.put(DAOFactory.FULLPATH, fullpathTextField.getText());
            daoTXT = (AlumnoDAOTxt) DAOFactory.getInstance().buildDAO(config);
            dao = daoTXT;
            
            alumnos = dao.findAll(false);            
            //alumnos = dao.findAll(incluirCheckBoxActionPerformed.isSelected());
            alumnosModel.setAlumnos(alumnos);
            alumnosModel.fireTableDataChanged();
        } catch (DAOException | DAOFactoryException ex) {
            Logger.getLogger(AlumnoGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_chooserButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int selectedRow = alumnosTable.getSelectedRow();
        if (selectedRow < 0) {
             JOptionPane.showMessageDialog(this, "Debe seleccionar un alumno para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
             return;
        }
         int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea dar de baja al alumno?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
         if (confirm != JOptionPane.YES_OPTION) {
             return;
         }
         int modelRow = alumnosTable.convertRowIndexToModel(selectedRow);
         Alumno alumnoSeleccionado = alumnos.get(modelRow);
         try {
            alumnoSeleccionado.setEstado('B');
            dao.update(alumnoSeleccionado);
            actualizarTabla();
            JOptionPane.showMessageDialog(this, "Alumno dado de baja correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } catch (DAOException | EstadoException ex) {
            Logger.getLogger(AlumnoGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error al dar de baja al alumno:\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void crearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearButtonActionPerformed
        AluDialog aluDialog = new AluDialog(this, true, CrudAction.CREATE, null);
        aluDialog.setVisible(true);

        System.out.println("Se cerró el dialogo");
        Alumno alu = aluDialog.getAlu();

        if (alu == null) {
            System.out.println("Creación cancelada por el usuario.");
            return;
        }

        try {
            dao.create(alu);
            //actualiza despues de creear
            actualizarTabla();
        } catch (DAOException ex) {
            Logger.getLogger(AlumnoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_crearButtonActionPerformed
    private void actualizarTabla() {
        try {
            alumnos = dao.findAll(true); 
            // Reutilizás el mismo modelo
            alumnosModel.setAlumnos(alumnos); 
            alumnosModel.fireTableDataChanged();
        } catch (DAOException ex) {
            Logger.getLogger(AlumnoGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error al actualizar la tabla:\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void modificarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarButtonActionPerformed
            
        int selectedRow = alumnosTable.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un alumno para modificar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
    // Obtengooo el alumno seleccionadooo
    //Alumno alumnoSeleccionado = alumnos.get(selectedRow);
    // convierte índice de la vista al modelo real
     int modelRow = alumnosTable.convertRowIndexToModel(selectedRow); 
     // obtiene el alumno desde la lista real según el índice convertido
     Alumno alumnoSeleccionado = alumnos.get(modelRow); 
    // abro el diálogo en modo UPDATE, con ese alumno
    AluDialog aluDialog = new AluDialog(this, true, CrudAction.UPDATE, alumnoSeleccionado);
    aluDialog.setVisible(true);
    // Obtener el alumno actualizado desde el diálogo
    Alumno alumnoModificado = aluDialog.getAlu();
    if (alumnoModificado == null) {
        System.out.println("Modificación cancelada por el usuario.");
        return;
    }
    try {
        dao.update(alumnoModificado);
        // refrescar tabla
        actualizarTabla(); 
        JOptionPane.showMessageDialog(this, "Alumno modificado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } catch (DAOException ex) {
        Logger.getLogger(AlumnoGUI.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Error al modificar el alumno:\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }        
    }//GEN-LAST:event_modificarButtonActionPerformed

    private void consultarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarButtonActionPerformed
        int selectedRow = alumnosTable.getSelectedRow();
        Alumno selectedAlu = alumnos.get(selectedRow);
        if (selectedRow <0){
            JOptionPane.showMessageDialog(this, "No se ha seleccionado un Alumno","Error",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        AluDialog aluDialog = new AluDialog(this, true, CrudAction.READ, selectedAlu);
        aluDialog.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarButtonActionPerformed

    private void connSQLButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connSQLButtonActionPerformed
                                        
        try {
            Map<String, String> config = new HashMap<>();
            config.put(DAOFactory.TIPO_DAO, "TIPO_DAO_SQL");
            config.put(DAOFactory.URL_SQL, "jdbc:mysql://localhost:3306/alumnos");
            config.put(DAOFactory.USER_SQL, userTextField.getText());
            config.put(DAOFactory.PASS_SQL, pwdTextField.getText());

            daoSQL = (AlumnoDAOSql) DAOFactory.getInstance().buildDAO(config);
            dao = daoSQL;

            alumnos = dao.findAll(false);
            alumnosModel.setAlumnos(alumnos);
            alumnosModel.fireTableDataChanged();

            JOptionPane.showMessageDialog(this, "Conectado a la base de datos correctamente", "Conexión exitosa", JOptionPane.INFORMATION_MESSAGE);

        } catch (DAOFactoryException | DAOException ex) {
            Logger.getLogger(AlumnoGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de conexión", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_connSQLButtonActionPerformed

    private void fullpathTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullpathTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullpathTextFieldActionPerformed

    private void incluirCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluirCheckBoxActionPerformed
         try {
        alumnos = dao.findAll(incluirCheckBox.isSelected());
        alumnosModel.setAlumnos(alumnos);
        alumnosModel.fireTableDataChanged();
    } catch (DAOException ex) {
        Logger.getLogger(AlumnoGUI.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Error al recargar alumnos", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_incluirCheckBoxActionPerformed

    private void urlTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urlTextFieldActionPerformed

    private void userTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextFieldActionPerformed

    private void pwdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlumnoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlumnoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlumnoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumnoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlumnoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable alumnosTable;
    private javax.swing.JButton chooserButton;
    private javax.swing.JButton connSQLButton;
    private javax.swing.JButton consultarButton;
    private javax.swing.JButton crearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField fullpathTextField;
    private javax.swing.JCheckBox incluirCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarButton;
    private javax.swing.JTextField pwdTextField;
    private javax.swing.JComboBox<String> repoComboBox;
    private javax.swing.JPanel sqlPanel;
    private javax.swing.JPanel txtPanel;
    private javax.swing.JTextField urlTextField;
    private javax.swing.JTextField userTextField;
    // End of variables declaration//GEN-END:variables
}
